services:
    db:
        image: postgres:9.6
        container_name: banking-app
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: banking-app

        ports:
            - 3001:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
